<?php

use Drupal\wbm3cm\Plugin\migrate\destination\EntityRevision;

/**
 * {@inheritdoc}
 */
function wbm3cm_migrate_destination_info_alter(&$definitions) {
  // If the entity_revision:* destination gets translations switched on
  // it throws an exception for every row because the langcode id is not
  // returned by getIds() but is returned by import()...
  foreach ($definitions as $id => $definition) {
    if (preg_match('/^entity_revision:/', $id)) {
      $definitions[$id]['class'] = EntityRevision::class;
    }
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function wbm3cm_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'entity_update' || $hook == 'entity_presave') {
    unset($implementations['workbench_moderation']);
  }
}
